# Generated by Django 4.1 on 2022-10-18 10:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=400)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(choices=[('a', 'жёлтый'), ('b', 'белый'), ('c', 'зелёный'), ('d', 'красный'), ('e', 'синий')], default='a', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('tag', models.ManyToManyField(blank=True, to='notebook.tags')),
            ],
            options={
                'ordering': ['-pinned', '-timestamp'],
            },
        ),
    ]
