# Generated by Django 4.1 on 2022-09-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_note_color_alter_note_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('a', 'жёлтый'), ('b', 'белый'), ('c', 'зелёный'), ('d', 'красный'), ('e', 'синий')], default='a', max_length=1),
        ),
    ]
